server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: book-store-eureka
  lifecycle:
    timeout-per-shutdown-phase: 10s
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: 1234

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
logging:
  file:
    path: ./logs